- name: Consul | Install Packages
  ansible.builtin.dnf: 
    name:
      - unzip
    state: latest
    update_cache: true

- name: Consul | Add user
  ansible.builtin.user:
    name: "consul"
    shell: "/bin/false"
    system: false
    create_home: false
      #    append: true
      #    groups:
      #    - nginx

- name: Consul | Copy consul binaries
  ansible.builtin.copy:
    src: consul_1.17.0_linux_amd64.zip
    dest: /tmp/consul_1.17.0_linux_amd64.zip

- name: Consul | Unarchive consul binaries
  ansible.builtin.unarchive:
    src: /tmp/consul_1.17.0_linux_amd64.zip
    dest: /usr/local/sbin
    remote_src: true

- name: Consul | Make directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: consul
    group: consul
  loop:
  - /etc/consul.d
  - /var/lib/consul

- name: Consul | Configure
  ansible.builtin.template:
    src: consul/consul-client.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
  notify: reload consul

- name: Consul | Configure Services
  ansible.builtin.template:
    src: consul/consul-service-app.hcl.j2
    dest: /etc/consul.d/services.hcl
    owner: consul
    group: consul
  notify: reload consul

- name: Consul | Copy systemd units
  ansible.builtin.copy:
    src: consul/consul.service
    dest: /etc/systemd/system/consul.service

- name: Consul | Start consul service
  ansible.builtin.systemd:
    name: consul
    state: restarted
    enabled: true
    daemon_reload: true

